### ISSUE TITLE
shd_support.glsl not found.

### ISSUE THREAD

**Issue by shujaatak** [installgentoo/opengl_gui#1]
shd_support.glsl is missing from the repository. 
I am trying to test opengl_gui project but shd_support.glsl is missing due to I can't test it. Can you upload that file please?

**Comment by installgentoo** [comment]
it's located in demo/proj/base_classes/shaders/ and it should be copied into bin dir automatically when you run cmake(see build_exec function in .cmake/util.cmake). it's my way of having shaders in qtcreator's project structure.

**Comment by shujaatak** [comment]
Going to try again and update you about the progress!

**Comment by installgentoo** [comment]
are you running cmake on windows perhaps? if it can't copy files you can just copy both .glsl files and proj/resources folder(not its contents - folder) into whereever binaries are.

**Comment by shujaatak** [comment]
You guessed rightly! Going to try that!

**Comment by installgentoo** [comment]
second glsl file is in proj/tester

**Comment by shujaatak** [comment]
OMG!!! It's AMAZING!

**Comment by shujaatak** [comment]
Can you please add **topics** to categorize your repository and make it more **discoverable** please?
This repository literally needs public attention!

**Comment by installgentoo** [comment]
how does one achieve that? i am a simple cat and posses no knowledge on this subject.

**Comment by shujaatak** [comment]
Just below the repository description there is a **Manage topics** link, click on that and then add topics/tags with spaces like this: opengl imgui gui ui tools toolkit gamedev

**Comment by installgentoo** [comment]
indeed. thank you for the instructions.

**Comment by shujaatak** [comment]
Can you please reformat the following line in the readme file:

> Running on linux: cd ./demo/demo/proj cmake ./ make -j4 cd ./bin ./tester_main

like this:

Running on linux:
$ git clone https://github.com/installgentoo/opengl_gui.git
$ cd opengl_gui/demo/proj/
$ cmake ./
$ make -j4 
$ cd ./bin
$ ./tester_main

**Comment by installgentoo** [comment]
what purpose does "$" serve?

**Comment by shujaatak** [comment]
In the above comment I mistakenly used a forked repository link but now I corrected it.

**Comment by shujaatak** [comment]
It lets the reader know that he/she has to use the command written after $ sign.

**Comment by shujaatak** [comment]
I think there is a typing mistake, Shouldn't it be **$ cd opengl_gui/demo/proj/** instead of **$ cd ./demo/demo/proj**?

**Comment by shujaatak** [comment]
In the readme file, shouldn't there be only one **demo/** in **$ cd ./opengl_gui/demo/demo/proj**?

**Comment by shujaatak** [comment]
I love this project and it's simplicity! I wish it become famous quickly as it deserves it!
